export const KEYCLOAK_REALM = "KEYCLOAK_REALM";
export const KEYCLOAK_URL = "KEYCLOAK_URL";
export const KEYCLOAK_CLIENT_ID = "KEYCLOAK_CLIENT_ID";
export const KEYCLOAK_CLIENT_SECRET = "KEYCLOAK_CLIENT_SECRET";
