CREATE TABLE "CLASSIFY_OPTION" (
    "id" BIGSERIAL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "classifyId" BIGINT NOT NULL,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,
    "createdBy" VARCHAR(255),
    "updatedBy" VARCHAR(255),
    "deletedBy" VARCHAR(255),
    CONSTRAINT fk_classify FOREIGN KEY ("classifyId") REFERENCES "CLASSIFY"("id") ON DELETE CASCADE
);

ALTER TABLE "CLASSIFY" DROP COLUMN "options";